import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageContextProvider from "@/context/PageContext";
import SessionProvider from "@/context/SessionContext";
import AllUserContextProvider from "@/context/AllUserContext";
import { getServerSession } from "next-auth";
import authOptions from "@/lib/config/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SparkStep",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="font-poppins bg-customgray">
        <SessionProvider session={session}>
          <AllUserContextProvider>
            <PageContextProvider>{children}</PageContextProvider>
          </AllUserContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
