import React from "react";

const StepsChartInfo = () => {
  return (
    <div className="px-8 py-6 rounded-lg absolute bg-white shadow-lg top-12 z-50">
      <p className="text-gray-800">
        This chart displays the total number of steps generated by the hardware
        and categorize the data for each day in a week.
      </p>
    </div>
  );
};

export default StepsChartInfo;
