"use client";

import React from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 20,
    fontSize: 12,
  },
  header: {
    alignItems: "center",
    marginBottom: 30,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: "50%",
    marginBottom: 8,
  },
  userName: {
    fontSize: 14,
    fontWeight: "bold",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 20,
    textAlign: "center",
  },
  section: {
    marginBottom: 30,
  },
  summaryCard: {
    padding: 10,
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    marginBottom: 20,
  },
  summaryItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  table: {
    display: "table",
    width: "100%",
    borderCollapse: "collapse",
    marginTop: 10,
  },
  tableRow: {
    flexDirection: "row",
    backgroundColor: "#f9f9f9",
  },
  tableHeader: {
    backgroundColor: "#e0e0e0",
    fontWeight: "bold",
  },
  tableCell: {
    flex: 1,
    border: "1px solid #ddd",
    padding: 8,
  },
  footer: {
    marginTop: 20,
    textAlign: "center",
    fontSize: 10,
    color: "#888",
  },
});

const UserReport = ({ user, summary, data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Image src={user.profilePicture} style={styles.profileImage} />
        <Text style={styles.userName}>{user.name}</Text>
        <Text style={styles.title}>User Activity Report</Text>
      </View>

      {/* Summary */}
      <View style={styles.summaryCard}>
        <Text style={{ marginBottom: 10, fontWeight: "bold" }}>Summary</Text>
        <View style={styles.summaryItem}>
          <Text>Total Voltage:</Text>
          <Text>{summary.totalVoltage}</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text>Total Steps:</Text>
          <Text>{summary.totalSteps}</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text>Average Voltage:</Text>
          <Text>{summary.averageVoltage}</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text>Peak Voltage:</Text>
          <Text>{summary.peakVoltage}</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text>Standard Deviation:</Text>
          <Text>{summary.standardDeviation}</Text>
        </View>
      </View>

      {/* Table */}
      <View style={styles.section}>
        <Text>Most Recent Data:</Text>
        <View style={styles.table}>
          <View style={[styles.tableRow, styles.tableHeader]}>
            <Text style={styles.tableCell}>Timestamp</Text>
            <Text style={styles.tableCell}>Voltage</Text>
            <Text style={styles.tableCell}>PSI</Text>
          </View>
          {data.map((row, index) => (
            <View
              style={[
                styles.tableRow,
                index % 2 === 0 ? { backgroundColor: "#fff" } : null,
              ]}
              key={index}
            >
              <Text style={styles.tableCell}>{row.timestamp}</Text>
              <Text style={styles.tableCell}>{row.voltage}</Text>
              <Text style={styles.tableCell}>{row.psi}</Text>
            </View>
          ))}
        </View>
      </View>

      {/* Footer */}
      <Text style={styles.footer}>Generated by SparkStep</Text>
    </Page>
  </Document>
);

export default UserReport;
