import React from "react";

const VoltageChartInfo = () => {
  return (
    <div className="px-8 py-12 rounded-lg absolute bg-white shadow-lg top-12 z-50">
      This chart renders the voltage generated by the footstep power generator
      hardware and displays it in a line chart. It divides the data into each
      day and shows the amount of voltage generated for each day.
    </div>
  );
};

export default VoltageChartInfo;
