import React from "react";

const VoltageChartInfo = () => {
  return (
    <div className="px-8 py-12 rounded-lg absolute bg-white shadow-lg top-12 z-50 text-sm">
      This section render charts with voltages generated by the footstep power
      generator hardware.
    </div>
  );
};

export default VoltageChartInfo;
