import Header from "@/components/Header";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

const Guide = async () => {
  const session = await getServerSession(authOptions);
  return (
    <>
      <Header session={session} />
      <div className="w-11/12 lg:w-8/12 m-auto lg:my-20 my-4 py-4 rounded-lg bg-white px-4">
        <div className="mb-8">
          <h1 className="font-bold mb-2">1. Detection of Footsteps</h1>
          <p className="text-sm">
            Piezoelectric sensors are strategically placed on walkways or floors
            where foot traffic occurs.
          </p>
          <p className="text-sm">
            When individuals step on these sensors, they generate mechanical
            stress, causing them to deform slightly and produce electrical
            charges.
          </p>
        </div>
        <div className="mb-8">
          <h1 className="font-bold mb-2">
            2. Conversion of Mechanical Energy to Electrical Energy
          </h1>
          <p className="text-sm">
            The deformation of the piezoelectric sensors under pressure
            generates small electrical voltages.
          </p>
          <p className="text-sm">
            These electrical charges are then collected and stored for
            conversion into usable electrical energy
          </p>
        </div>
        <div className="mb-8">
          <h1 className="font-bold mb-2">3. Signal Processing with Arduino</h1>
          <p className="text-sm">
            The Arduino microcontroller processes the electrical signals
            generated by the piezoelectric sensors.
          </p>
          <p className="text-sm">
            Analog-to-digital conversion enables the Arduino to interpret the
            magnitude and frequency of the footstep-generated electrical
            signals.
          </p>
        </div>
        <div className="mb-8">
          <h1 className="font-bold mb-2">4. Energy Regulation and Storage</h1>
          <p className="text-sm">
            The processed electrical signals are regulated to ensure stable
            power output.
          </p>
          <p className="text-sm">
            Capacitors and voltage regulators are used to store and stabilize
            the generated electrical energy.
          </p>
        </div>
        <div className="mb-8">
          <h1 className="font-bold mb-2">
            5. Power Distribution and Utilization
          </h1>
          <p className="text-sm">
            The stored electrical energy can be utilized to power low-energy
            devices directly or stored in batteries for future use.
          </p>
          <p className="text-sm">
            LED indicators may be integrated to visually display the
            availability of generated power.
          </p>
        </div>
        <div className="mb-8">
          <h1 className="font-bold mb-2">6. Optimization and Efficiency</h1>
          <p className="text-sm">
            Continuous monitoring and optimization techniques are employed to
            maximize energy harvesting efficiency.
          </p>
          <p className="text-sm">
            Calibration of sensors and adjustments to signal processing
            algorithms contribute to enhanced performance and reliability.
          </p>
        </div>

        <div className="mb-8">
          <h1 className="font-bold mb-2">
            7. Integration with Existing Infrastructure
          </h1>
          <p className="text-sm">
            The footstep power generator can be seamlessly integrated into
            existing infrastructure, such as sidewalks, corridors, or public
            spaces.
          </p>
          <p className="text-sm">
            Its non-intrusive design allows for easy installation and minimal
            disruption to the surrounding environment.
          </p>
        </div>
        <div className="mb-8">
          <h1 className="font-bold mb-2">8. Scalability and Adaptability</h1>
          <p className="text-sm">
            The modular design of the system enables scalability to accommodate
            various foot traffic volumes and environments.
          </p>
          <p className="text-sm">
            Customization options allow for adaptation to specific project
            requirements and objectives.
          </p>
        </div>
        <div className="mb-8">
          <h1 className="font-bold mb-2">9. Real-World Applications</h1>
          <ul className="text-sm">
            <li>Public spaces: parks, shopping malls, airports</li>
            <li>Transportation hubs: train stations, bus terminals</li>
            <li>Urban environments: sidewalks, pedestrian bridges</li>
          </ul>
        </div>
        <div className="mb-8">
          <h1 className="font-bold mb-2">10. Environmental Impact</h1>
          <p className="text-sm">
            By harnessing renewable energy from human motion, the footstep power
            generator contributes to reducing carbon emissions and promoting
            sustainable energy practices.
          </p>
          <p className="text-sm">
            It serves as a tangible example of harnessing clean energy from
            everyday activities.
          </p>
        </div>
      </div>
    </>
  );
};

export default Guide;
